# Generated by Django 5.2.5 on 2025-08-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0002_pollmodel_is_ended_uservote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
